site_name: Geometry Central
theme:
  name: 'material'
  palette:
    primary: 'yellow'
    accent: 'red'
markdown_extensions:
  - codehilite
  - admonition
  - markdown.extensions.footnotes
  - markdown.extensions.smarty
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.arithmatex

extra:
  search:
    tokenizer: '[\s\-\.::]+'

extra_css:
  - extras.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

repo_name: 'nmwsharp/geometry-central'
repo_url: 'https://github.com/nmwsharp/geometry-central'

pages:
  - Home: 'index.md'
  - Build: 
    - 'Building' : 'build/build.md'
    - 'Tests' : 'build/tests.md'
  - Halfedge Mesh: 
    - 'Basics' : 'halfedge_mesh/basics.md'
    - 'Boundaries' : 'halfedge_mesh/boundaries.md'
    - 'Navigation and Iteration' : 'halfedge_mesh/navigation.md'
    - 'Containers' : 'halfedge_mesh/containers.md'
    - 'I/O' : 'halfedge_mesh/io.md'
    - 'Mutation' : 'halfedge_mesh/mutation.md'
    - 'Delta Complexes' : 'halfedge_mesh/delta_complex.md'
    - 'Internals' : 'halfedge_mesh/internals.md'
  - Geometry: 
    - 'Intrinsic Geometry' : 'geometry/intrinsic_geometry.md'
  - Linear Algebra: 
    - 'Matrix Types' : 'linear_algebra/matrix_types.md'
    - 'Utilities' : 'linear_algebra/utilities.md'
    - 'Solvers' : 'linear_algebra/solvers.md'
  - Algorithms: 
    - 'Direction Fields' : 'algorithms/direction_fields.md'
    - 'Distance' : 'algorithms/distance.md'
    - 'Mesh Graph Algorithms' : 'algorithms/mesh_graph_algorithms.md'
  - Utilities: 
    - 'Vector Types' : 'utilities/vector_types.md'

